# Generated by Django 5.1.7 on 2025-11-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='owner',
        ),
    ]
