# Generated by Django 5.1.7 on 2026-08-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='email_enviado',
            field=models.BooleanField(default=False, help_text='Evita mandar el recordatorio diario más de una vez para el mismo aviso.'),
        ),
    ]
