# Generated by Django 5.1.7 on 2026-08-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_barrio_propiedad_cocheras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('alquilado', 'Alquilado'), ('reservado', 'Reservado')], default='disponible', max_length=20),
        ),
    ]
