# Generated by Django 5.1.7 on 2026-08-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_historiallead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
