# Generated by Django 5.1.7 on 2026-08-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_evento_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_buscada', models.CharField(blank=True, help_text='venta, alquiler, etc.', max_length=50, null=True)),
                ('tipo_de_propiedad', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('presupuesto_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('presupuesto_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(blank=True, default='USD', max_length=10, null=True)),
                ('ambientes_min', models.PositiveIntegerField(blank=True, null=True)),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia', to='leads.contacto')),
            ],
        ),
    ]
