# Generated by Django 5.1.7 on 2026-08-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_preferenciabusqueda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferenciabusqueda',
            options={'verbose_name': 'Preferencia de búsqueda', 'verbose_name_plural': 'Preferencias de búsqueda'},
        ),
        migrations.RemoveField(
            model_name='preferenciabusqueda',
            name='operacion_buscada',
        ),
        migrations.AddField(
            model_name='preferenciabusqueda',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='preferenciabusqueda',
            name='barrio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferenciabusqueda',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferenciabusqueda',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='preferenciabusqueda',
            name='tipo_de_propiedad',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('ph', 'Ph'), ('terreno', 'Terreno'), ('cochera', 'Cochera'), ('local', 'Local'), ('oficina', 'Oficina'), ('consultorio', 'Consultorio'), ('quinta', 'Quinta'), ('chacra', 'Chacra'), ('galpon', 'Galpon'), ('deposito', 'Deposito'), ('campo', 'Campo'), ('hotel', 'Hotel'), ('fondo de comercio', 'Fondo de Comercio'), ('edificio', 'Edificio'), ('otro', 'Otro')], default='', max_length=50),
        ),
    ]
