# Generated by Django 5.1.7 on 2026-08-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_preferenciabusqueda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferenciabusqueda',
            options={'ordering': ['-id'], 'verbose_name': 'Preferencia de búsqueda', 'verbose_name_plural': 'Preferencias de búsqueda'},
        ),
        migrations.AddField(
            model_name='preferenciabusqueda',
            name='etiqueta',
            field=models.CharField(blank=True, default='', help_text="Nombre corto para diferenciar este criterio de otros del mismo lead (ej: 'Casa para vivir').", max_length=100),
        ),
        migrations.AlterField(
            model_name='preferenciabusqueda',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='leads.contacto'),
        ),
    ]
