# Generated by Django 5.1.7 on 2026-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_preferenciabusqueda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciabusqueda',
            name='operacion',
            field=models.CharField(blank=True, choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], default='', help_text='Si busca comprar o alquilar. Vacío = cualquiera de las dos.', max_length=20),
        ),
    ]
